"""Static fixture data for financial instruments used in the Wealth Advisory Lab.

Covers all OpenWealth FinancialInstrumentType values:
equity, bond, fund, commodity, realEstate, alternative, cryptoAsset,
preciousMetal, future, option, index, fxForward, fxSwap, fxOption, other.

ISINs are plausible-looking but fictional and not guaranteed to be valid.
"""

INSTRUMENTS: list[dict] = [
    # -------------------------------------------------------------------------
    # EQUITIES – Swiss (~15)
    # -------------------------------------------------------------------------
    {
        "id": "EQ-001", "isin": "CH0012221716", "name": "Novartis AG",
        "short_name": "NOVN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 92.50,
        "yield_pct": None,
        "description": "Swiss multinational pharmaceutical company headquartered in Basel.",
    },
    {
        "id": "EQ-002", "isin": "CH0038863350", "name": "Nestlé SA",
        "short_name": "NESN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "consumer_staples",
        "coupon_pct": None, "maturity_date": None, "price": 97.80,
        "yield_pct": None,
        "description": "World's largest food and beverage company based in Vevey, Switzerland.",
    },
    {
        "id": "EQ-003", "isin": "CH0244767585", "name": "UBS Group AG",
        "short_name": "UBSG", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 28.14,
        "yield_pct": None,
        "description": "Swiss multinational investment bank and financial services company.",
    },
    {
        "id": "EQ-004", "isin": "CH0012221400", "name": "ABB Ltd",
        "short_name": "ABBN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 46.30,
        "yield_pct": None,
        "description": "Swedish-Swiss multinational corporation in electrification and automation.",
    },
    {
        "id": "EQ-005", "isin": "CH0012032048", "name": "Roche Holding AG",
        "short_name": "ROG", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 232.40,
        "yield_pct": None,
        "description": "Swiss multinational healthcare company active in pharmaceuticals and diagnostics.",
    },
    {
        "id": "EQ-006", "isin": "CH0126881561", "name": "Swiss Re AG",
        "short_name": "SREN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 108.65,
        "yield_pct": None,
        "description": "Leading wholesale provider of reinsurance, insurance and risk transfer solutions.",
    },
    {
        "id": "EQ-007", "isin": "CH0011075394", "name": "Zurich Insurance Group AG",
        "short_name": "ZURN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 518.20,
        "yield_pct": None,
        "description": "Global insurance company providing general and life insurance products.",
    },
    {
        "id": "EQ-008", "isin": "CH0210483332", "name": "Compagnie Financière Richemont SA",
        "short_name": "CFR", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 116.75,
        "yield_pct": None,
        "description": "Swiss luxury goods holding company owning Cartier, IWC and other brands.",
    },
    {
        "id": "EQ-009", "isin": "CH0418792922", "name": "Sika AG",
        "short_name": "SIKA", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "materials",
        "coupon_pct": None, "maturity_date": None, "price": 215.30,
        "yield_pct": None,
        "description": "Swiss specialty chemicals company focused on construction and industry.",
    },
    {
        "id": "EQ-010", "isin": "CH0012214059", "name": "Holcim Ltd",
        "short_name": "HOLN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "materials",
        "coupon_pct": None, "maturity_date": None, "price": 78.90,
        "yield_pct": None,
        "description": "World's largest building materials company producing cement, concrete and aggregates.",
    },
    {
        "id": "EQ-011", "isin": "CH0244767403", "name": "Partners Group Holding AG",
        "short_name": "PGHN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 1245.00,
        "yield_pct": None,
        "description": "Global private markets investment management firm headquartered in Baar.",
    },
    {
        "id": "EQ-012", "isin": "CH0012214081", "name": "Lonza Group AG",
        "short_name": "LONN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 487.60,
        "yield_pct": None,
        "description": "Swiss multinational chemicals and biotechnology company serving pharma and biotech.",
    },
    {
        "id": "EQ-013", "isin": "CH0023405456", "name": "SGS SA",
        "short_name": "SGSN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 74.42,
        "yield_pct": None,
        "description": "World's leading testing, inspection and certification company.",
    },
    {
        "id": "EQ-014", "isin": "CH0008742519", "name": "Givaudan SA",
        "short_name": "GIVN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "materials",
        "coupon_pct": None, "maturity_date": None, "price": 2980.00,
        "yield_pct": None,
        "description": "World's largest flavours and fragrances company headquartered in Vernier.",
    },
    {
        "id": "EQ-015", "isin": "CH0044328745", "name": "Geberit AG",
        "short_name": "GEBN", "type": "equity", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 468.50,
        "yield_pct": None,
        "description": "European market leader in sanitary products and building drainage systems.",
    },
    # -------------------------------------------------------------------------
    # EQUITIES – German (~10)
    # -------------------------------------------------------------------------
    {
        "id": "EQ-016", "isin": "DE0007164600", "name": "SAP SE",
        "short_name": "SAP", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "technology",
        "coupon_pct": None, "maturity_date": None, "price": 198.40,
        "yield_pct": None,
        "description": "Germany's largest software company providing enterprise resource planning solutions.",
    },
    {
        "id": "EQ-017", "isin": "DE0007236101", "name": "Siemens AG",
        "short_name": "SIE", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 174.82,
        "yield_pct": None,
        "description": "German multinational technology conglomerate in automation, electrification and digitalization.",
    },
    {
        "id": "EQ-018", "isin": "DE0005140008", "name": "Deutsche Bank AG",
        "short_name": "DBK", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 14.62,
        "yield_pct": None,
        "description": "Germany's largest bank providing investment, corporate and retail banking services.",
    },
    {
        "id": "EQ-019", "isin": "DE0005190003", "name": "Bayerische Motoren Werke AG",
        "short_name": "BMW", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 84.30,
        "yield_pct": None,
        "description": "German multinational manufacturer of luxury vehicles and motorcycles.",
    },
    {
        "id": "EQ-020", "isin": "DE0008404005", "name": "Allianz SE",
        "short_name": "ALV", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 298.60,
        "yield_pct": None,
        "description": "Germany's largest insurance company and one of Europe's largest financial services groups.",
    },
    {
        "id": "EQ-021", "isin": "DE000BASF111", "name": "BASF SE",
        "short_name": "BAS", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "materials",
        "coupon_pct": None, "maturity_date": None, "price": 42.18,
        "yield_pct": None,
        "description": "World's largest chemical producer with operations across Europe, Americas and Asia.",
    },
    {
        "id": "EQ-022", "isin": "DE000BAY0017", "name": "Bayer AG",
        "short_name": "BAYN", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 24.75,
        "yield_pct": None,
        "description": "German multinational pharmaceutical and life sciences company.",
    },
    {
        "id": "EQ-023", "isin": "DE0005552004", "name": "Deutsche Telekom AG",
        "short_name": "DTE", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "communication_services",
        "coupon_pct": None, "maturity_date": None, "price": 26.94,
        "yield_pct": None,
        "description": "Germany's largest telecommunications provider with global operations.",
    },
    {
        "id": "EQ-024", "isin": "DE0007030009", "name": "Volkswagen AG Pref.",
        "short_name": "VOW3", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 98.16,
        "yield_pct": None,
        "description": "Germany's largest automaker operating brands including Audi, Porsche and Škoda.",
    },
    {
        "id": "EQ-025", "isin": "DE0005785604", "name": "Fresenius SE & Co. KGaA",
        "short_name": "FRE", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 29.10,
        "yield_pct": None,
        "description": "German healthcare group providing infusion therapy, dialysis and hospital services.",
    },
    # -------------------------------------------------------------------------
    # EQUITIES – French (~8)
    # -------------------------------------------------------------------------
    {
        "id": "EQ-026", "isin": "FR0000121014", "name": "LVMH Moët Hennessy Louis Vuitton SE",
        "short_name": "MC", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 620.80,
        "yield_pct": None,
        "description": "World's largest luxury goods conglomerate owning over 75 prestigious brands.",
    },
    {
        "id": "EQ-027", "isin": "FR0014000MR3", "name": "TotalEnergies SE",
        "short_name": "TTE", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "energy",
        "coupon_pct": None, "maturity_date": None, "price": 58.72,
        "yield_pct": None,
        "description": "French multinational integrated energy company operating across oil, gas and renewables.",
    },
    {
        "id": "EQ-028", "isin": "FR0000131104", "name": "BNP Paribas SA",
        "short_name": "BNP", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 64.38,
        "yield_pct": None,
        "description": "France's largest bank and leading European financial services group.",
    },
    {
        "id": "EQ-029", "isin": "FR0000120628", "name": "AXA SA",
        "short_name": "CS", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 34.96,
        "yield_pct": None,
        "description": "French multinational insurance firm and one of the world's largest insurers.",
    },
    {
        "id": "EQ-030", "isin": "FR0000120073", "name": "Airbus SE",
        "short_name": "AIR", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 158.30,
        "yield_pct": None,
        "description": "European multinational aerospace corporation and world's largest commercial aircraft manufacturer.",
    },
    {
        "id": "EQ-031", "isin": "FR0000120271", "name": "L'Oréal SA",
        "short_name": "OR", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "consumer_staples",
        "coupon_pct": None, "maturity_date": None, "price": 368.50,
        "yield_pct": None,
        "description": "World's largest cosmetics company with brands across hair care, skincare and makeup.",
    },
    {
        "id": "EQ-032", "isin": "FR0000125486", "name": "Vinci SA",
        "short_name": "DG", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 104.20,
        "yield_pct": None,
        "description": "French multinational concessions and construction company.",
    },
    {
        "id": "EQ-033", "isin": "FR0000131906", "name": "Schneider Electric SE",
        "short_name": "SU", "type": "equity", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 218.40,
        "yield_pct": None,
        "description": "French multinational providing energy management and industrial automation solutions.",
    },
    # -------------------------------------------------------------------------
    # EQUITIES – US (~20)
    # -------------------------------------------------------------------------
    {
        "id": "EQ-034", "isin": "US0378331005", "name": "Apple Inc.",
        "short_name": "AAPL", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "technology",
        "coupon_pct": None, "maturity_date": None, "price": 213.50,
        "yield_pct": None,
        "description": "World's most valuable technology company producing iPhone, Mac and services.",
    },
    {
        "id": "EQ-035", "isin": "US5949181045", "name": "Microsoft Corporation",
        "short_name": "MSFT", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "technology",
        "coupon_pct": None, "maturity_date": None, "price": 418.30,
        "yield_pct": None,
        "description": "American multinational technology company in software, cloud and productivity tools.",
    },
    {
        "id": "EQ-036", "isin": "US4592001014", "name": "JPMorgan Chase & Co.",
        "short_name": "JPM", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 218.90,
        "yield_pct": None,
        "description": "Largest US bank providing investment banking, financial services and asset management.",
    },
    {
        "id": "EQ-037", "isin": "US4781601046", "name": "Johnson & Johnson",
        "short_name": "JNJ", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 154.70,
        "yield_pct": None,
        "description": "American multinational pharmaceutical and medical devices corporation.",
    },
    {
        "id": "EQ-038", "isin": "US0846707026", "name": "Berkshire Hathaway Inc. Class B",
        "short_name": "BRK.B", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 438.20,
        "yield_pct": None,
        "description": "American multinational conglomerate holding company led by Warren Buffett.",
    },
    {
        "id": "EQ-039", "isin": "US0231351067", "name": "Amazon.com Inc.",
        "short_name": "AMZN", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 188.40,
        "yield_pct": None,
        "description": "American multinational technology company in e-commerce, cloud and digital streaming.",
    },
    {
        "id": "EQ-040", "isin": "US02079K3059", "name": "Alphabet Inc. Class A",
        "short_name": "GOOGL", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "communication_services",
        "coupon_pct": None, "maturity_date": None, "price": 174.60,
        "yield_pct": None,
        "description": "American multinational technology conglomerate owning Google and YouTube.",
    },
    {
        "id": "EQ-041", "isin": "US30303M1027", "name": "Meta Platforms Inc.",
        "short_name": "META", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "communication_services",
        "coupon_pct": None, "maturity_date": None, "price": 512.80,
        "yield_pct": None,
        "description": "American social media and technology conglomerate owning Facebook, Instagram and WhatsApp.",
    },
    {
        "id": "EQ-042", "isin": "US92826C8394", "name": "Visa Inc.",
        "short_name": "V", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 278.50,
        "yield_pct": None,
        "description": "American multinational payment technology corporation processing digital transactions.",
    },
    {
        "id": "EQ-043", "isin": "US88160R1014", "name": "Tesla Inc.",
        "short_name": "TSLA", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 248.90,
        "yield_pct": None,
        "description": "American electric vehicle and clean energy company.",
    },
    {
        "id": "EQ-044", "isin": "US7170811035", "name": "Pfizer Inc.",
        "short_name": "PFE", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 27.40,
        "yield_pct": None,
        "description": "American multinational pharmaceutical and biotechnology corporation.",
    },
    {
        "id": "EQ-045", "isin": "US30231G1022", "name": "Exxon Mobil Corporation",
        "short_name": "XOM", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "energy",
        "coupon_pct": None, "maturity_date": None, "price": 114.30,
        "yield_pct": None,
        "description": "American multinational oil and gas corporation.",
    },
    {
        "id": "EQ-046", "isin": "US7427181091", "name": "Procter & Gamble Co.",
        "short_name": "PG", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "consumer_staples",
        "coupon_pct": None, "maturity_date": None, "price": 168.50,
        "yield_pct": None,
        "description": "American multinational consumer goods corporation.",
    },
    {
        "id": "EQ-047", "isin": "US1912161007", "name": "The Coca-Cola Company",
        "short_name": "KO", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "consumer_staples",
        "coupon_pct": None, "maturity_date": None, "price": 63.80,
        "yield_pct": None,
        "description": "American multinational beverage corporation and manufacturer of Coca-Cola.",
    },
    {
        "id": "EQ-048", "isin": "US0605051046", "name": "Bank of America Corporation",
        "short_name": "BAC", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 42.10,
        "yield_pct": None,
        "description": "American multinational investment bank and financial services company.",
    },
    {
        "id": "EQ-049", "isin": "US67066G1040", "name": "NVIDIA Corporation",
        "short_name": "NVDA", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "technology",
        "coupon_pct": None, "maturity_date": None, "price": 875.40,
        "yield_pct": None,
        "description": "American multinational technology company designing GPUs and system-on-chip units.",
    },
    {
        "id": "EQ-050", "isin": "US6541061031", "name": "Nike Inc.",
        "short_name": "NKE", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 75.20,
        "yield_pct": None,
        "description": "American multinational corporation in athletic footwear, apparel and equipment.",
    },
    {
        "id": "EQ-051", "isin": "US4370761029", "name": "Honeywell International Inc.",
        "short_name": "HON", "type": "equity", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": "industrials",
        "coupon_pct": None, "maturity_date": None, "price": 198.60,
        "yield_pct": None,
        "description": "American multinational conglomerate in aerospace, building technologies and performance materials.",
    },
    {
        "id": "EQ-052", "isin": "US1667641005", "name": "Chevron Corporation",
        "short_name": "CVX", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "energy",
        "coupon_pct": None, "maturity_date": None, "price": 148.70,
        "yield_pct": None,
        "description": "American multinational energy corporation engaged in oil and gas exploration.",
    },
    {
        "id": "EQ-053", "isin": "US2546871060", "name": "Walt Disney Co.",
        "short_name": "DIS", "type": "equity", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "communication_services",
        "coupon_pct": None, "maturity_date": None, "price": 88.30,
        "yield_pct": None,
        "description": "American multinational entertainment and media conglomerate.",
    },
    # -------------------------------------------------------------------------
    # EQUITIES – UK, JP, Other (~7)
    # -------------------------------------------------------------------------
    {
        "id": "EQ-054", "isin": "GB0005405286", "name": "HSBC Holdings plc",
        "short_name": "HSBA", "type": "equity", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": "financials",
        "coupon_pct": None, "maturity_date": None, "price": 742.80,
        "yield_pct": None,
        "description": "British multinational investment bank and financial services holding company.",
    },
    {
        "id": "EQ-055", "isin": "GB0007980591", "name": "BP plc",
        "short_name": "BP.", "type": "equity", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": "energy",
        "coupon_pct": None, "maturity_date": None, "price": 428.10,
        "yield_pct": None,
        "description": "British multinational oil and gas company.",
    },
    {
        "id": "EQ-056", "isin": "GB00B03MLX29", "name": "Shell plc",
        "short_name": "SHEL", "type": "equity", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": "energy",
        "coupon_pct": None, "maturity_date": None, "price": 2682.00,
        "yield_pct": None,
        "description": "British-Dutch multinational oil and gas company.",
    },
    {
        "id": "EQ-057", "isin": "JP3633400001", "name": "Toyota Motor Corporation",
        "short_name": "7203", "type": "equity", "currency": "JPY",
        "exchange": "TSE", "country": "JP", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 2986.00,
        "yield_pct": None,
        "description": "Japanese multinational automotive manufacturer and the world's largest carmaker.",
    },
    {
        "id": "EQ-058", "isin": "JP6758270006", "name": "Sony Group Corporation",
        "short_name": "6758", "type": "equity", "currency": "JPY",
        "exchange": "TSE", "country": "JP", "sector": "consumer_discretionary",
        "coupon_pct": None, "maturity_date": None, "price": 12480.00,
        "yield_pct": None,
        "description": "Japanese multinational conglomerate in electronics, entertainment and financial services.",
    },
    {
        "id": "EQ-059", "isin": "KR7005930003", "name": "Samsung Electronics Co. Ltd GDR",
        "short_name": "SMSNG", "type": "equity", "currency": "USD",
        "exchange": "LSE", "country": "KR", "sector": "technology",
        "coupon_pct": None, "maturity_date": None, "price": 1312.00,
        "yield_pct": None,
        "description": "South Korean multinational electronics and semiconductor conglomerate.",
    },
    {
        "id": "EQ-060", "isin": "GB0031348658", "name": "AstraZeneca plc",
        "short_name": "AZN", "type": "equity", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": "healthcare",
        "coupon_pct": None, "maturity_date": None, "price": 11820.00,
        "yield_pct": None,
        "description": "British-Swedish multinational pharmaceutical and biopharmaceutical company.",
    },
    # -------------------------------------------------------------------------
    # BONDS – Government (~15)
    # -------------------------------------------------------------------------
    {
        "id": "BD-001", "isin": "CH0214430827", "name": "Swiss Confederation Bond 0.5% 2030",
        "short_name": "CH-GOVT", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 0.5, "maturity_date": "2030-06-27", "price": 98.20,
        "yield_pct": 0.72,
        "description": "Swiss federal government bond denominated in CHF.",
    },
    {
        "id": "BD-002", "isin": "CH0224397213", "name": "Swiss Confederation Bond 1.0% 2033",
        "short_name": "CH-GOVT2", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 1.0, "maturity_date": "2033-08-10", "price": 96.45,
        "yield_pct": 1.18,
        "description": "Medium-term Swiss Confederation bond offering modest CHF yield.",
    },
    {
        "id": "BD-003", "isin": "DE0001102572", "name": "Bundesrepublik Deutschland 2.30% 2033",
        "short_name": "BUND33", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": 2.3, "maturity_date": "2033-02-15", "price": 100.62,
        "yield_pct": 2.24,
        "description": "German federal government bond (Bund) with 2.30% coupon maturing 2033.",
    },
    {
        "id": "BD-004", "isin": "DE0001135481", "name": "Bundesrepublik Deutschland 1.70% 2032",
        "short_name": "BUND32", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": 1.7, "maturity_date": "2032-08-15", "price": 97.30,
        "yield_pct": 2.06,
        "description": "German Bund with 1.70% coupon used as benchmark for EUR sovereign debt.",
    },
    {
        "id": "BD-005", "isin": "US912810TM57", "name": "US Treasury Note 4.125% 2027",
        "short_name": "UST27", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 4.125, "maturity_date": "2027-10-31", "price": 100.18,
        "yield_pct": 4.08,
        "description": "US Treasury note maturing October 2027 with quarterly coupon.",
    },
    {
        "id": "BD-006", "isin": "US912810ST87", "name": "US Treasury Bond 3.875% 2035",
        "short_name": "UST35", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 3.875, "maturity_date": "2035-02-15", "price": 99.40,
        "yield_pct": 3.94,
        "description": "Long-term US Treasury bond backed by the full faith and credit of the US government.",
    },
    {
        "id": "BD-007", "isin": "FR0013451507", "name": "OAT France 1.50% 2031",
        "short_name": "OAT31", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": None,
        "coupon_pct": 1.5, "maturity_date": "2031-05-25", "price": 95.50,
        "yield_pct": 2.22,
        "description": "French Treasury bond (OAT) issued by the Republic of France.",
    },
    {
        "id": "BD-008", "isin": "FR0014001NN8", "name": "OAT France 2.75% 2034",
        "short_name": "OAT34", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": None,
        "coupon_pct": 2.75, "maturity_date": "2034-10-25", "price": 98.60,
        "yield_pct": 2.90,
        "description": "Medium-term French government bond denominated in EUR.",
    },
    {
        "id": "BD-009", "isin": "GB00BYY5F144", "name": "UK Gilt 1.00% 2032",
        "short_name": "GILT32", "type": "bond", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": None,
        "coupon_pct": 1.0, "maturity_date": "2032-01-22", "price": 88.40,
        "yield_pct": 3.72,
        "description": "UK government gilt with 1% coupon, used as benchmark for GBP sovereign debt.",
    },
    {
        "id": "BD-010", "isin": "GB00BFWFPN62", "name": "UK Gilt 4.25% 2034",
        "short_name": "GILT34", "type": "bond", "currency": "GBP",
        "exchange": "LSE", "country": "GB", "sector": None,
        "coupon_pct": 4.25, "maturity_date": "2034-12-07", "price": 102.10,
        "yield_pct": 4.04,
        "description": "UK Treasury gilt maturing December 2034.",
    },
    # -------------------------------------------------------------------------
    # BONDS – Corporate (~15)
    # -------------------------------------------------------------------------
    {
        "id": "BD-011", "isin": "CH0421893671", "name": "Nestlé Finance 0.75% 2027",
        "short_name": "NESN27", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 0.75, "maturity_date": "2027-04-12", "price": 98.90,
        "yield_pct": 1.02,
        "description": "CHF-denominated corporate bond issued by Nestlé Finance International.",
    },
    {
        "id": "BD-012", "isin": "US037833DL45", "name": "Apple Inc. 3.00% 2029",
        "short_name": "AAPL29", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 3.0, "maturity_date": "2029-06-20", "price": 97.50,
        "yield_pct": 3.38,
        "description": "Senior unsecured bond issued by Apple Inc. in USD.",
    },
    {
        "id": "BD-013", "isin": "US38141GHK91", "name": "Goldman Sachs 4.25% 2026",
        "short_name": "GS26", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 4.25, "maturity_date": "2026-10-21", "price": 100.40,
        "yield_pct": 4.10,
        "description": "Senior USD bond issued by The Goldman Sachs Group Inc.",
    },
    {
        "id": "BD-014", "isin": "DE000A1HLTD3", "name": "Volkswagen Financial 3.50% 2027",
        "short_name": "VW-FIN", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": 3.5, "maturity_date": "2027-03-15", "price": 100.10,
        "yield_pct": 3.48,
        "description": "EUR corporate bond issued by Volkswagen Financial Services AG.",
    },
    {
        "id": "BD-015", "isin": "FR0013348257", "name": "TotalEnergies Capital 2.875% 2026",
        "short_name": "TTEF26", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": None,
        "coupon_pct": 2.875, "maturity_date": "2026-09-29", "price": 99.80,
        "yield_pct": 2.93,
        "description": "EUR-denominated bond issued by TotalEnergies Capital International.",
    },
    {
        "id": "BD-016", "isin": "CH0251232462", "name": "UBS AG 2.00% 2028",
        "short_name": "UBSG28", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 2.0, "maturity_date": "2028-01-20", "price": 97.70,
        "yield_pct": 2.38,
        "description": "Senior preferred CHF bond issued by UBS AG.",
    },
    {
        "id": "BD-017", "isin": "DE000A1TNAP6", "name": "Siemens Financieringsmaatschappij 1.25% 2027",
        "short_name": "SIE27", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": 1.25, "maturity_date": "2027-06-23", "price": 97.30,
        "yield_pct": 2.02,
        "description": "EUR senior bond issued by Siemens group financing entity.",
    },
    {
        "id": "BD-018", "isin": "US172967MU09", "name": "Citigroup 4.00% 2028",
        "short_name": "C28", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 4.0, "maturity_date": "2028-03-01", "price": 99.10,
        "yield_pct": 4.14,
        "description": "Senior USD bond issued by Citigroup Inc.",
    },
    {
        "id": "BD-019", "isin": "GB00B3FMT040", "name": "HSBC Holdings 6.00% 2027 (USD)",
        "short_name": "HSBA27", "type": "bond", "currency": "USD",
        "exchange": None, "country": "GB", "sector": None,
        "coupon_pct": 6.0, "maturity_date": "2027-05-22", "price": 103.50,
        "yield_pct": 4.92,
        "description": "USD senior bond issued by HSBC Holdings plc.",
    },
    {
        "id": "BD-020", "isin": "LU2388699148", "name": "Pictet Group 1.875% 2030",
        "short_name": "PICTET", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "LU", "sector": None,
        "coupon_pct": 1.875, "maturity_date": "2030-09-18", "price": 96.80,
        "yield_pct": 2.30,
        "description": "CHF bond issued by Pictet Group to fund private banking activities.",
    },
    {
        "id": "BD-021", "isin": "US882508AZ48", "name": "Texas Instruments 4.15% 2029",
        "short_name": "TXN29", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 4.15, "maturity_date": "2029-05-15", "price": 100.30,
        "yield_pct": 4.10,
        "description": "Senior unsecured bond issued by Texas Instruments Incorporated.",
    },
    {
        "id": "BD-022", "isin": "US912828ZL55", "name": "US Treasury Inflation-Protected 0.625% 2030",
        "short_name": "TIPS30", "type": "bond", "currency": "USD",
        "exchange": None, "country": "US", "sector": None,
        "coupon_pct": 0.625, "maturity_date": "2030-01-15", "price": 96.80,
        "yield_pct": 1.15,
        "description": "US Treasury Inflation-Protected Security with principal adjusted for CPI.",
    },
    {
        "id": "BD-023", "isin": "DE000A2G9EM5", "name": "KfW Bank 0.375% 2028",
        "short_name": "KFW28", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": 0.375, "maturity_date": "2028-01-11", "price": 94.20,
        "yield_pct": 1.46,
        "description": "EUR bond issued by Germany's state-owned development bank KfW.",
    },
    {
        "id": "BD-024", "isin": "CH0312525379", "name": "Roche Holdings 0.50% 2031",
        "short_name": "ROG31", "type": "bond", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 0.5, "maturity_date": "2031-03-14", "price": 94.60,
        "yield_pct": 1.08,
        "description": "CHF bond issued by Roche Holdings Ltd.",
    },
    {
        "id": "BD-025", "isin": "FR0013374006", "name": "LVMH Moët Hennessy 1.125% 2026",
        "short_name": "MC26", "type": "bond", "currency": "EUR",
        "exchange": "XETRA", "country": "FR", "sector": None,
        "coupon_pct": 1.125, "maturity_date": "2026-04-10", "price": 99.40,
        "yield_pct": 1.40,
        "description": "EUR-denominated bond issued by LVMH Moët Hennessy Louis Vuitton SE.",
    },
    # -------------------------------------------------------------------------
    # FUNDS – ETFs (~15)
    # -------------------------------------------------------------------------
    {
        "id": "FD-001", "isin": "US78462F1030", "name": "SPDR S&P 500 ETF Trust",
        "short_name": "SPY", "type": "fund", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 524.30,
        "yield_pct": 1.28,
        "description": "World's largest ETF tracking the S&P 500 index of US large-cap equities.",
    },
    {
        "id": "FD-002", "isin": "US46090E1038", "name": "Invesco QQQ Trust",
        "short_name": "QQQ", "type": "fund", "currency": "USD",
        "exchange": "NASDAQ", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 448.20,
        "yield_pct": 0.56,
        "description": "ETF tracking the NASDAQ-100 index of largest non-financial companies.",
    },
    {
        "id": "FD-003", "isin": "IE00B4L5Y983", "name": "iShares Core MSCI World UCITS ETF",
        "short_name": "IWDA", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 94.50,
        "yield_pct": 1.42,
        "description": "UCITS ETF providing low-cost exposure to global developed market equities.",
    },
    {
        "id": "FD-004", "isin": "LU0629459743", "name": "UBS ETF (CH) - SMI",
        "short_name": "UBSMI", "type": "fund", "currency": "CHF",
        "exchange": "SIX", "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 132.60,
        "yield_pct": 2.10,
        "description": "Swiss ETF tracking the Swiss Market Index (SMI) of Switzerland's 20 largest companies.",
    },
    {
        "id": "FD-005", "isin": "IE00B3RBWM25", "name": "Vanguard FTSE All-World UCITS ETF",
        "short_name": "VWRD", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 112.80,
        "yield_pct": 1.65,
        "description": "UCITS ETF tracking 4000+ stocks across developed and emerging markets globally.",
    },
    {
        "id": "FD-006", "isin": "IE00B52MJY50", "name": "iShares Core MSCI Emerging Markets IMI UCITS ETF",
        "short_name": "EIMI", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 30.40,
        "yield_pct": 2.18,
        "description": "UCITS ETF providing broad exposure to large, mid and small-cap emerging market stocks.",
    },
    {
        "id": "FD-007", "isin": "LU0274208692", "name": "Xtrackers MSCI Europe UCITS ETF",
        "short_name": "XEUR", "type": "fund", "currency": "EUR",
        "exchange": "XETRA", "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 75.30,
        "yield_pct": 2.86,
        "description": "ETF tracking the MSCI Europe index of large and mid-cap European equities.",
    },
    {
        "id": "FD-008", "isin": "IE00B3XXRP09", "name": "iShares Barclays USD Treasury Bond ETF",
        "short_name": "IBTM", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 88.40,
        "yield_pct": 3.92,
        "description": "UCITS ETF providing exposure to US Treasury bonds with intermediate maturities.",
    },
    {
        "id": "FD-009", "isin": "LU0290358497", "name": "iShares Euro Corporate Bond UCITS ETF",
        "short_name": "IEAC", "type": "fund", "currency": "EUR",
        "exchange": "XETRA", "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 108.90,
        "yield_pct": 3.15,
        "description": "ETF tracking EUR-denominated investment-grade corporate bonds.",
    },
    {
        "id": "FD-010", "isin": "LU0832435464", "name": "Amundi MSCI Japan UCITS ETF",
        "short_name": "AMJPN", "type": "fund", "currency": "JPY",
        "exchange": "XETRA", "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 54.20,
        "yield_pct": 1.78,
        "description": "ETF tracking the MSCI Japan index of large and mid-cap Japanese equities.",
    },
    # -------------------------------------------------------------------------
    # FUNDS – Active / Private bank branded (~10)
    # -------------------------------------------------------------------------
    {
        "id": "FD-011", "isin": "LU0048578792", "name": "Pictet-Global Megatrend Selection P EUR",
        "short_name": "PICT-GM", "type": "fund", "currency": "EUR",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 236.80,
        "yield_pct": None,
        "description": "Actively managed equity fund investing in global megatrend themes managed by Pictet.",
    },
    {
        "id": "FD-012", "isin": "LU0255978064", "name": "UBS (Lux) Equity Fund – Global Sustainable (CHF)",
        "short_name": "UBSESG", "type": "fund", "currency": "CHF",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 182.40,
        "yield_pct": None,
        "description": "Actively managed sustainable equity fund with global mandate managed by UBS.",
    },
    {
        "id": "FD-013", "isin": "LU0394720949", "name": "Lombard Odier Funds – Global Climate Bond",
        "short_name": "LO-CLIM", "type": "fund", "currency": "EUR",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 98.30,
        "yield_pct": 3.40,
        "description": "Bond fund investing in climate-aligned issuers managed by Lombard Odier.",
    },
    {
        "id": "FD-014", "isin": "LU0048461898", "name": "Pictet-CHF Bonds P",
        "short_name": "PICT-B", "type": "fund", "currency": "CHF",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 134.60,
        "yield_pct": 1.18,
        "description": "CHF-denominated bond fund focused on investment-grade Swiss issuers managed by Pictet.",
    },
    {
        "id": "FD-015", "isin": "LU0071073671", "name": "UBS (Lux) Bond Fund – EUR High Yield",
        "short_name": "UBS-HY", "type": "fund", "currency": "EUR",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 86.50,
        "yield_pct": 6.40,
        "description": "Actively managed high-yield EUR bond fund managed by UBS Asset Management.",
    },
    {
        "id": "FD-016", "isin": "LU0157151653", "name": "Julius Baer Multistock – Swiss Stock Fund B",
        "short_name": "JB-CH", "type": "fund", "currency": "CHF",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 312.50,
        "yield_pct": None,
        "description": "Active Swiss equity fund investing in SMI and SPI constituents managed by Julius Baer.",
    },
    {
        "id": "FD-017", "isin": "LU1900195648", "name": "Vontobel Fund – mtx Sustainable Emerging Markets Leaders",
        "short_name": "VON-EM", "type": "fund", "currency": "USD",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 128.40,
        "yield_pct": None,
        "description": "Sustainable emerging markets equity fund managed by Vontobel Asset Management.",
    },
    {
        "id": "FD-018", "isin": "IE00B4ND3602", "name": "iShares MSCI AC Far East ex-Japan UCITS ETF",
        "short_name": "IAFE", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 36.80,
        "yield_pct": 2.46,
        "description": "UCITS ETF providing exposure to Asia-Pacific equities excluding Japan.",
    },
    {
        "id": "FD-019", "isin": "LU0839027447", "name": "Credit Suisse Fund – Systematic Fixed Income CHF",
        "short_name": "CS-FI", "type": "fund", "currency": "CHF",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 108.20,
        "yield_pct": 1.54,
        "description": "Systematically managed fixed-income fund investing in CHF investment-grade bonds.",
    },
    {
        "id": "FD-020", "isin": "IE00B1FZSB30", "name": "iShares S&P 500 USD Dividend Aristocrats UCITS ETF",
        "short_name": "IDVY", "type": "fund", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 62.40,
        "yield_pct": 3.18,
        "description": "ETF tracking S&P 500 Dividend Aristocrats with 25+ consecutive years of dividend growth.",
    },
    # -------------------------------------------------------------------------
    # COMMODITIES (~12)
    # -------------------------------------------------------------------------
    {
        "id": "CM-001", "isin": "US06744CAA01", "name": "WTI Crude Oil (spot proxy)",
        "short_name": "CL-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 82.40,
        "yield_pct": None,
        "description": "West Texas Intermediate crude oil spot-price reference instrument.",
    },
    {
        "id": "CM-002", "isin": "US0680561011", "name": "Brent Crude Oil (spot proxy)",
        "short_name": "CO-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 86.10,
        "yield_pct": None,
        "description": "Brent crude oil spot-price reference instrument used for global benchmark pricing.",
    },
    {
        "id": "CM-003", "isin": "US0680561029", "name": "Henry Hub Natural Gas (spot proxy)",
        "short_name": "NG-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 2.86,
        "yield_pct": None,
        "description": "Natural gas spot-price reference at Henry Hub delivery point in Louisiana.",
    },
    {
        "id": "CM-004", "isin": "US0680561037", "name": "CBOT Corn (spot proxy)",
        "short_name": "ZC-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 446.50,
        "yield_pct": None,
        "description": "Chicago corn spot-price reference in US cents per bushel.",
    },
    {
        "id": "CM-005", "isin": "US0680561045", "name": "CBOT Wheat (spot proxy)",
        "short_name": "ZW-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 590.25,
        "yield_pct": None,
        "description": "Chicago soft red winter wheat spot-price reference in US cents per bushel.",
    },
    {
        "id": "CM-006", "isin": "US0680561053", "name": "CBOT Soybeans (spot proxy)",
        "short_name": "ZS-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 1186.00,
        "yield_pct": None,
        "description": "Chicago soybean spot-price reference in US cents per bushel.",
    },
    {
        "id": "CM-007", "isin": "US0680561061", "name": "LME Copper (spot proxy)",
        "short_name": "HG-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 4.28,
        "yield_pct": None,
        "description": "London Metal Exchange copper spot-price reference in USD per pound.",
    },
    {
        "id": "CM-008", "isin": "US0680561079", "name": "LME Aluminium (spot proxy)",
        "short_name": "AL-SPOT", "type": "commodity", "currency": "USD",
        "exchange": "CME", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 2340.00,
        "yield_pct": None,
        "description": "London Metal Exchange aluminium spot-price reference in USD per metric tonne.",
    },
    {
        "id": "CM-009", "isin": "IE00B5ZR2F28", "name": "iShares Bloomberg Roll Select Commodity Swap UCITS ETF",
        "short_name": "ROLL", "type": "commodity", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 32.40,
        "yield_pct": None,
        "description": "UCITS ETF providing diversified exposure to commodity futures with an optimised roll strategy.",
    },
    {
        "id": "CM-010", "isin": "DE000A0H0728", "name": "ETFS WTI Crude Oil ETC",
        "short_name": "CRUD", "type": "commodity", "currency": "USD",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 43.80,
        "yield_pct": None,
        "description": "Exchange-traded commodity providing exposure to WTI crude oil futures.",
    },
    {
        "id": "CM-011", "isin": "DE000A0KRJX4", "name": "ETFS Natural Gas ETC",
        "short_name": "NGAS", "type": "commodity", "currency": "USD",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 6.14,
        "yield_pct": None,
        "description": "Exchange-traded commodity providing exposure to Henry Hub natural gas futures.",
    },
    {
        "id": "CM-012", "isin": "DE000A0KRJ24", "name": "ETFS Corn ETC",
        "short_name": "CORN", "type": "commodity", "currency": "USD",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 4.22,
        "yield_pct": None,
        "description": "Exchange-traded commodity providing exposure to CBOT corn futures.",
    },
    # -------------------------------------------------------------------------
    # REAL ESTATE (~10)
    # -------------------------------------------------------------------------
    {
        "id": "RE-001", "isin": "US9229085538", "name": "Vanguard Real Estate Index Fund ETF",
        "short_name": "VNQ", "type": "realEstate", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 88.40,
        "yield_pct": 4.30,
        "description": "ETF tracking US REIT index providing diversified exposure to US commercial real estate.",
    },
    {
        "id": "RE-002", "isin": "IE00B1FZS350", "name": "iShares Developed Markets Property Yield UCITS ETF",
        "short_name": "IWDP", "type": "realEstate", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 22.80,
        "yield_pct": 3.86,
        "description": "UCITS ETF providing exposure to global developed market property companies and REITs.",
    },
    {
        "id": "RE-003", "isin": "CH0012410517", "name": "CS REF Siat Swiss Real Estate Fund",
        "short_name": "CSREFSIAT", "type": "realEstate", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 218.40,
        "yield_pct": 2.84,
        "description": "Swiss real estate fund investing in Swiss residential and commercial properties.",
    },
    {
        "id": "RE-004", "isin": "CH0024608827", "name": "UBS (CH) Property Fund – Swiss Residential",
        "short_name": "UBSRESI", "type": "realEstate", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 62.80,
        "yield_pct": 2.60,
        "description": "Swiss real estate fund specialising in residential properties across Switzerland.",
    },
    {
        "id": "RE-005", "isin": "LU0274210672", "name": "Xtrackers FTSE Developed Europe Real Estate UCITS ETF",
        "short_name": "XDER", "type": "realEstate", "currency": "EUR",
        "exchange": "XETRA", "country": "LU", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 18.60,
        "yield_pct": 3.42,
        "description": "ETF tracking developed European property companies and REITs.",
    },
    {
        "id": "RE-006", "isin": "CH0419041497", "name": "Baloise Swiss Property Fund",
        "short_name": "BALPROP", "type": "realEstate", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 172.20,
        "yield_pct": 3.10,
        "description": "Swiss open-ended real estate fund managed by Baloise Group.",
    },
    {
        "id": "RE-007", "isin": "IE00B5BFJG71", "name": "iShares Asia Property Yield UCITS ETF",
        "short_name": "IASP", "type": "realEstate", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 28.40,
        "yield_pct": 4.10,
        "description": "UCITS ETF providing exposure to REITs and real estate companies across Asia-Pacific.",
    },
    {
        "id": "RE-008", "isin": "LU0192223062", "name": "Pictet-Real Estate Securities P EUR",
        "short_name": "PICT-RE", "type": "realEstate", "currency": "EUR",
        "exchange": None, "country": "LU", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 148.60,
        "yield_pct": 3.28,
        "description": "Actively managed European real estate securities fund managed by Pictet.",
    },
    {
        "id": "RE-009", "isin": "CH0354251993", "name": "Helvetia Swiss Real Estate Fund",
        "short_name": "HELVRE", "type": "realEstate", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 114.40,
        "yield_pct": 2.92,
        "description": "Swiss real estate fund managed by Helvetia Insurance investing in domestic properties.",
    },
    {
        "id": "RE-010", "isin": "US70604L1098", "name": "Prologis Inc.",
        "short_name": "PLD", "type": "realEstate", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": "real_estate",
        "coupon_pct": None, "maturity_date": None, "price": 114.80,
        "yield_pct": 3.44,
        "description": "World's largest logistics real estate investment trust owning industrial warehouses.",
    },
    # -------------------------------------------------------------------------
    # ALTERNATIVE (~8)
    # -------------------------------------------------------------------------
    {
        "id": "AL-001", "isin": "LU0328476556", "name": "Man AHL Diversified Futures Fund Ltd",
        "short_name": "MANAHL", "type": "alternative", "currency": "USD",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 124.60,
        "yield_pct": None,
        "description": "Systematic trend-following fund using algorithmic trading across diversified futures markets.",
    },
    {
        "id": "AL-002", "isin": "LU0255981076", "name": "UBS (Lux) Alternative Beta Fund",
        "short_name": "UBS-ALT", "type": "alternative", "currency": "USD",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 108.30,
        "yield_pct": None,
        "description": "Multi-strategy alternative fund providing hedge fund-like returns via liquid instruments.",
    },
    {
        "id": "AL-003", "isin": "LU0834774838", "name": "Pictet-Multi Asset Global Opportunities P",
        "short_name": "PICT-MA", "type": "alternative", "currency": "USD",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 136.80,
        "yield_pct": None,
        "description": "Flexible multi-asset fund accessing global opportunities including alternatives managed by Pictet.",
    },
    {
        "id": "AL-004", "isin": "IE00BD0Q9284", "name": "WisdomTree Enhanced Commodity UCITS ETF",
        "short_name": "WCOB", "type": "alternative", "currency": "USD",
        "exchange": "LSE", "country": "IE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 38.60,
        "yield_pct": None,
        "description": "Enhanced commodity ETF using optimised commodity roll strategy across broad commodity spectrum.",
    },
    {
        "id": "AL-005", "isin": "LU1548497426", "name": "Lombard Odier – All Roads Growth Fund",
        "short_name": "LO-ARG", "type": "alternative", "currency": "CHF",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 118.40,
        "yield_pct": None,
        "description": "Multi-asset risk-premia fund providing diversified alternative exposures managed by Lombard Odier.",
    },
    {
        "id": "AL-006", "isin": "LU0946159626", "name": "Partners Group Private Equity SICAV",
        "short_name": "PG-PE", "type": "alternative", "currency": "EUR",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 214.80,
        "yield_pct": None,
        "description": "Semi-liquid private equity SICAV providing access to buyout and growth equity strategies.",
    },
    {
        "id": "AL-007", "isin": "CH0413209520", "name": "SwissRE Cat Bond Fund",
        "short_name": "SRCATB", "type": "alternative", "currency": "USD",
        "exchange": None, "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 128.90,
        "yield_pct": 6.80,
        "description": "Fund investing in insurance-linked securities and catastrophe bonds.",
    },
    {
        "id": "AL-008", "isin": "LU0174119429", "name": "Bluecrest Capital Management Fixed Income Alpha",
        "short_name": "BC-FIA", "type": "alternative", "currency": "USD",
        "exchange": None, "country": "LU", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 142.30,
        "yield_pct": None,
        "description": "Macro fixed-income strategy targeting absolute returns via relative value and directional trades.",
    },
    # -------------------------------------------------------------------------
    # CRYPTO ASSETS (~8)
    # -------------------------------------------------------------------------
    {
        "id": "CR-001", "isin": "CH0454664001", "name": "Bitcoin (BTC)",
        "short_name": "BTC", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 62480.00,
        "yield_pct": None,
        "description": "World's first and largest cryptocurrency by market capitalisation.",
    },
    {
        "id": "CR-002", "isin": "CH0454664019", "name": "Ethereum (ETH)",
        "short_name": "ETH", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 3248.00,
        "yield_pct": None,
        "description": "Decentralised smart-contract blockchain platform and its native cryptocurrency.",
    },
    {
        "id": "CR-003", "isin": "CH0454664027", "name": "BNB (Binance Coin)",
        "short_name": "BNB", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 412.00,
        "yield_pct": None,
        "description": "Native utility token of the Binance exchange and BNB Chain ecosystem.",
    },
    {
        "id": "CR-004", "isin": "CH0454664035", "name": "Solana (SOL)",
        "short_name": "SOL", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 168.40,
        "yield_pct": None,
        "description": "High-performance layer-1 blockchain supporting DeFi and NFT applications.",
    },
    {
        "id": "CR-005", "isin": "CH0454664043", "name": "Cardano (ADA)",
        "short_name": "ADA", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 0.48,
        "yield_pct": None,
        "description": "Proof-of-stake blockchain platform focused on security and scalability.",
    },
    {
        "id": "CR-006", "isin": "CH0454664051", "name": "XRP (Ripple)",
        "short_name": "XRP", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 0.624,
        "yield_pct": None,
        "description": "Digital payment protocol and cryptocurrency for cross-border financial transactions.",
    },
    {
        "id": "CR-007", "isin": "CH0454664069", "name": "Polkadot (DOT)",
        "short_name": "DOT", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 7.82,
        "yield_pct": None,
        "description": "Multi-chain protocol enabling interoperability between different blockchains.",
    },
    {
        "id": "CR-008", "isin": "CH0454664077", "name": "Polygon (MATIC)",
        "short_name": "MATIC", "type": "cryptoAsset", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 0.724,
        "yield_pct": None,
        "description": "Ethereum layer-2 scaling solution providing faster and cheaper transactions.",
    },
    # -------------------------------------------------------------------------
    # PRECIOUS METALS (~5)
    # -------------------------------------------------------------------------
    {
        "id": "PM-001", "isin": "CH0047533523", "name": "Gold Spot (XAU/USD)",
        "short_name": "GOLD", "type": "preciousMetal", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 2348.00,
        "yield_pct": None,
        "description": "London Bullion Market spot gold price per troy ounce.",
    },
    {
        "id": "PM-002", "isin": "CH0047533531", "name": "Silver Spot (XAG/USD)",
        "short_name": "SILVER", "type": "preciousMetal", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 28.42,
        "yield_pct": None,
        "description": "London Bullion Market spot silver price per troy ounce.",
    },
    {
        "id": "PM-003", "isin": "CH0047533549", "name": "Platinum Spot (XPT/USD)",
        "short_name": "PLAT", "type": "preciousMetal", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 1048.00,
        "yield_pct": None,
        "description": "London Platinum and Palladium Market spot platinum price per troy ounce.",
    },
    {
        "id": "PM-004", "isin": "CH0047533556", "name": "Palladium Spot (XPD/USD)",
        "short_name": "PALL", "type": "preciousMetal", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 1028.00,
        "yield_pct": None,
        "description": "London Platinum and Palladium Market spot palladium price per troy ounce.",
    },
    {
        "id": "PM-005", "isin": "US4642851053", "name": "iShares Gold Trust ETF",
        "short_name": "IAU", "type": "preciousMetal", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 46.84,
        "yield_pct": None,
        "description": "US gold ETF providing cost-effective exposure to physical gold bullion.",
    },
    # -------------------------------------------------------------------------
    # FUTURES (~5)
    # -------------------------------------------------------------------------
    {
        "id": "FT-001", "isin": "US78378X1072", "name": "E-mini S&P 500 Futures (ES) Dec-2024",
        "short_name": "ESZ24", "type": "future", "currency": "USD",
        "exchange": "CME", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2024-12-20", "price": 5248.00,
        "yield_pct": None,
        "description": "CME E-mini S&P 500 equity index futures contract expiring December 2024.",
    },
    {
        "id": "FT-002", "isin": "US67066G2039", "name": "E-mini NASDAQ-100 Futures (NQ) Dec-2024",
        "short_name": "NQZ24", "type": "future", "currency": "USD",
        "exchange": "CME", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2024-12-20", "price": 18240.00,
        "yield_pct": None,
        "description": "CME E-mini NASDAQ-100 equity index futures contract expiring December 2024.",
    },
    {
        "id": "FT-003", "isin": "US06744C2006", "name": "WTI Crude Oil Futures (CL) Jan-2025",
        "short_name": "CLF25", "type": "future", "currency": "USD",
        "exchange": "CME", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2025-01-22", "price": 81.60,
        "yield_pct": None,
        "description": "CME WTI crude oil futures contract for January 2025 delivery.",
    },
    {
        "id": "FT-004", "isin": "US3812901030", "name": "Gold Futures (GC) Feb-2025",
        "short_name": "GCG25", "type": "future", "currency": "USD",
        "exchange": "CME", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2025-02-27", "price": 2356.00,
        "yield_pct": None,
        "description": "CME COMEX gold futures contract for February 2025 delivery.",
    },
    {
        "id": "FT-005", "isin": "DE0008469016", "name": "Euro Stoxx 50 Futures (FESX) Dec-2024",
        "short_name": "FESXZ24", "type": "future", "currency": "EUR",
        "exchange": "EUREX", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": "2024-12-20", "price": 4812.00,
        "yield_pct": None,
        "description": "Eurex Euro Stoxx 50 index futures contract expiring December 2024.",
    },
    # -------------------------------------------------------------------------
    # OPTIONS (~5)
    # -------------------------------------------------------------------------
    {
        "id": "OPT-001", "isin": "US78462F1048", "name": "SPY Call Option 540 Jan-2025",
        "short_name": "SPY540C", "type": "option", "currency": "USD",
        "exchange": "CBOE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2025-01-17", "price": 8.40,
        "yield_pct": None,
        "description": "Exchange-traded call option on SPY ETF with strike 540 expiring January 2025.",
    },
    {
        "id": "OPT-002", "isin": "US78462F1056", "name": "SPY Put Option 480 Jan-2025",
        "short_name": "SPY480P", "type": "option", "currency": "USD",
        "exchange": "CBOE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2025-01-17", "price": 6.20,
        "yield_pct": None,
        "description": "Exchange-traded put option on SPY ETF with strike 480 expiring January 2025.",
    },
    {
        "id": "OPT-003", "isin": "US0378331023", "name": "Apple Call Option 230 Dec-2024",
        "short_name": "AAPL230C", "type": "option", "currency": "USD",
        "exchange": "CBOE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": "2024-12-20", "price": 4.60,
        "yield_pct": None,
        "description": "Exchange-traded call option on Apple stock with strike 230 expiring December 2024.",
    },
    {
        "id": "OPT-004", "isin": "DE0008469024", "name": "ODAX Euro Stoxx 50 Call 5000 Dec-2024",
        "short_name": "DAX5KC", "type": "option", "currency": "EUR",
        "exchange": "EUREX", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": "2024-12-20", "price": 62.40,
        "yield_pct": None,
        "description": "Eurex call option on Euro Stoxx 50 index with strike 5000 expiring December 2024.",
    },
    {
        "id": "OPT-005", "isin": "CH0012221717", "name": "NOVN Novartis Put Option 85 Mar-2025",
        "short_name": "NOVN85P", "type": "option", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": "2025-03-21", "price": 1.82,
        "yield_pct": None,
        "description": "SIX exchange-traded put option on Novartis AG with strike CHF 85 expiring March 2025.",
    },
    # -------------------------------------------------------------------------
    # INDICES (~5)
    # -------------------------------------------------------------------------
    {
        "id": "IX-001", "isin": "CH0009980894", "name": "Swiss Market Index (SMI)",
        "short_name": "SMI", "type": "index", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 11680.00,
        "yield_pct": 2.20,
        "description": "Switzerland's blue-chip stock market index comprising 20 largest SIX-listed companies.",
    },
    {
        "id": "IX-002", "isin": "DE0008469008", "name": "DAX Performance Index",
        "short_name": "DAX", "type": "index", "currency": "EUR",
        "exchange": "XETRA", "country": "DE", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 18420.00,
        "yield_pct": 2.80,
        "description": "Germany's primary stock market index comprising 40 largest XETRA-listed companies.",
    },
    {
        "id": "IX-003", "isin": "US2605661048", "name": "S&P 500 Index",
        "short_name": "SPX", "type": "index", "currency": "USD",
        "exchange": "NYSE", "country": "US", "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 5248.00,
        "yield_pct": 1.30,
        "description": "US large-cap equity index comprising 500 leading publicly-traded US companies.",
    },
    {
        "id": "IX-004", "isin": "EU0009658145", "name": "Euro Stoxx 50 Index",
        "short_name": "SX5E", "type": "index", "currency": "EUR",
        "exchange": "EUREX", "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 4820.00,
        "yield_pct": 2.90,
        "description": "Eurozone blue-chip index comprising 50 largest companies from 20 Eurozone countries.",
    },
    {
        "id": "IX-005", "isin": "US6311011000", "name": "MSCI World Index",
        "short_name": "MXWO", "type": "index", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": None, "price": 3480.00,
        "yield_pct": 1.60,
        "description": "Global benchmark index covering large and mid-cap equities across 23 developed markets.",
    },
    # -------------------------------------------------------------------------
    # FX FORWARDS (~4)
    # -------------------------------------------------------------------------
    {
        "id": "FXF-001", "isin": None, "name": "EUR/CHF Forward 3M",
        "short_name": "EURCHFF", "type": "fxForward", "currency": "CHF",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-02-14", "price": 0.9524,
        "yield_pct": None,
        "description": "Three-month EUR/CHF forward contract locking in exchange rate for EUR purchase in CHF.",
    },
    {
        "id": "FXF-002", "isin": None, "name": "USD/CHF Forward 3M",
        "short_name": "USDCHFF", "type": "fxForward", "currency": "CHF",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-02-14", "price": 0.8842,
        "yield_pct": None,
        "description": "Three-month USD/CHF forward contract locking in exchange rate for USD purchase in CHF.",
    },
    {
        "id": "FXF-003", "isin": None, "name": "GBP/USD Forward 6M",
        "short_name": "GBPUSDF", "type": "fxForward", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-05-14", "price": 1.2680,
        "yield_pct": None,
        "description": "Six-month GBP/USD forward contract used to hedge sterling receivables into USD.",
    },
    {
        "id": "FXF-004", "isin": None, "name": "EUR/USD Forward 6M",
        "short_name": "EURUSDF", "type": "fxForward", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-05-14", "price": 1.0842,
        "yield_pct": None,
        "description": "Six-month EUR/USD forward contract for hedging European equity exposure into USD.",
    },
    # -------------------------------------------------------------------------
    # FX SWAPS (~2)
    # -------------------------------------------------------------------------
    {
        "id": "FXS-001", "isin": None, "name": "EUR/USD FX Swap 1Y",
        "short_name": "EURUSD1Y", "type": "fxSwap", "currency": "USD",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-11-14", "price": 1.0810,
        "yield_pct": None,
        "description": "One-year EUR/USD cross-currency swap exchanging EUR and USD cash flows.",
    },
    {
        "id": "FXS-002", "isin": None, "name": "EUR/CHF FX Swap 1Y",
        "short_name": "EURCHF1Y", "type": "fxSwap", "currency": "CHF",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-11-14", "price": 0.9490,
        "yield_pct": None,
        "description": "One-year EUR/CHF cross-currency swap exchanging EUR and CHF cash flows.",
    },
    # -------------------------------------------------------------------------
    # FX OPTIONS (~2)
    # -------------------------------------------------------------------------
    {
        "id": "FXO-001", "isin": None, "name": "EUR/CHF Call Option 0.97 Mar-2025",
        "short_name": "EURCHFC", "type": "fxOption", "currency": "CHF",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-03-14", "price": 0.0124,
        "yield_pct": None,
        "description": "EUR/CHF vanilla call option with strike 0.97 providing right to buy EUR at 0.97 CHF.",
    },
    {
        "id": "FXO-002", "isin": None, "name": "USD/CHF Put Option 0.88 Mar-2025",
        "short_name": "USDCHFP", "type": "fxOption", "currency": "CHF",
        "exchange": None, "country": None, "sector": None,
        "coupon_pct": None, "maturity_date": "2025-03-14", "price": 0.0098,
        "yield_pct": None,
        "description": "USD/CHF vanilla put option with strike 0.88 providing right to sell USD at 0.88 CHF.",
    },
    # -------------------------------------------------------------------------
    # OTHER (~4)
    # -------------------------------------------------------------------------
    {
        "id": "OT-001", "isin": "CH0373666809", "name": "Swiss Life Group Convertible Bond 1.00% 2028",
        "short_name": "SLN-CV", "type": "other", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": 1.0, "maturity_date": "2028-06-14", "price": 108.40,
        "yield_pct": 0.42,
        "description": "Convertible bond issued by Swiss Life Group convertible into Swiss Life shares.",
    },
    {
        "id": "OT-002", "isin": "CH0308307985", "name": "Leonteq Capital Protection Note on SMI",
        "short_name": "LTQ-CPN", "type": "other", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": "2026-12-15", "price": 101.20,
        "yield_pct": None,
        "description": "Structured capital protection note on the SMI with 100% principal protection at maturity.",
    },
    {
        "id": "OT-003", "isin": "CH0410772831", "name": "UBS PERLES Tracker on MSCI EM",
        "short_name": "UBSPER", "type": "other", "currency": "USD",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": "2027-06-20", "price": 88.60,
        "yield_pct": None,
        "description": "UBS PERLES tracker certificate providing 1:1 exposure to MSCI Emerging Markets Index.",
    },
    {
        "id": "OT-004", "isin": "CH0374146817", "name": "Vontobel Autocall Note on Nestlé",
        "short_name": "VON-AC", "type": "other", "currency": "CHF",
        "exchange": "SIX", "country": "CH", "sector": None,
        "coupon_pct": None, "maturity_date": "2026-03-18", "price": 96.40,
        "yield_pct": 6.20,
        "description": "Autocall note on Nestlé AG paying conditional coupon with early redemption feature.",
    },
]
