"""OpenWealth-style custodian data service."""

from .schemas import (
    Account,
    AccountReference,
    AccountType,
    AssetAllocation,
    CurrencyAmount,
    Customer,
    CustomerSegment,
    CustomerSnapshot,
    CustomerStatus,
    FinancialInstrument,
    FinancialInstrumentType,
    ForeignExchangeRate,
    InvestmentStrategy,
    MandateType,
    Movement,
    MovementType,
    PortfolioInformation,
    PriceType,
    Quantity,
    QuantityUnit,
    Transaction,
    TransactionType,
    Valuation,
    ValuatedPosition,
    ValuationPrice,
)
from .reference import build_reference
from .service import CustodianService
from .store import DuckDBCustodianStore, InMemoryCustodianStore, PostgresCustodianStore

__all__ = [
    "Account",
    "AccountReference",
    "AccountType",
    "AssetAllocation",
    "CurrencyAmount",
    "Customer",
    "CustomerSegment",
    "CustomerSnapshot",
    "CustomerStatus",
    "CustodianService",
    "DuckDBCustodianStore",
    "FinancialInstrument",
    "FinancialInstrumentType",
    "ForeignExchangeRate",
    "InMemoryCustodianStore",
    "InvestmentStrategy",
    "MandateType",
    "Movement",
    "MovementType",
    "PortfolioInformation",
    "PostgresCustodianStore",
    "PriceType",
    "Quantity",
    "QuantityUnit",
    "Transaction",
    "TransactionType",
    "Valuation",
    "ValuatedPosition",
    "ValuationPrice",
    "build_reference",
]
